### PR TITLE
[V1.3] Contacts: Added findphone, findname and findaddress commands

### PR DESCRIPTION
**Pull request by T0roloco**

### CODE REVIEW

**Comment by QzSG** [comment]
@T0roloco Mind resolving the conflict? Not sure which one is the correct one u need

**Comment by T0roloco** [comment]
> @T0roloco Mind resolving the conflict? Not sure which one is the correct one u need

@QzSG  Hmm...strange. For some reason I don't have the line:
  
             commandList.add(FindCommand.COMMAND_WORD + " KEYWORD");
in my version of main. Not really what that line does, not sure what do do here. Should I try to update my version of main and just copy the classes I've created? I haven't done tests for those classes yet, but the commands I added work as intended

**Comment by T0roloco** [comment]
Btw I'm pretty sure the FindCommand class can be deleted since i added the other commands. I just decided not to since I'm thinking of creating a superclass and make the other three subclasses

**Review by QzSG — APPROVED** [review]

**Review by QzSG — APPROVED** [review]
Looks good for now. Would be nice to add some unit tests in future pull requests so that we can be sure adding these commands did not break the others (also that it works as expected).

Some of the predicate methods look similar, once you are done with everything else and if there is time maybe you could look into making them more generic, for now its okay!

(Bypassing strict checks since Github outage stops webhooks from being sent so travis could not run build & tests but AppVeyor passed)

**Comment by QzSG** [comment]
Relevant #63

**Pull request merged**
